title: Fountain City Church - Overland Park, KS
description: |-
  Experience real community and meaningful relationships at Fountain City Church. Worship with Christ-centered followers who desire to know and glorify God and serve their community.

logos:
  main: /media/logos/fountain-city-church.svg
  kids: /media/logos/fcc-kids-and-families.svg

contact:
  email: james@fountaincitykc.org
  phone: 303-618-3079

serviceAddress:
  text: Sunday Service
  address: 8788 Metcalf Ave, Overland Park, KS 66212

mailingAddress:
  text: Mailing Address
  address: PO Box 7521, Overland Park, KS 66207

directions:
  text: Get directions
  href: https://maps.app.goo.gl/yRLoeGU1QisTNYLP9

connect:
  headline: Interested in Fountain City Church?
  content: |-
    Visiting a new church can be difficult. We'd love to connect and answer any questions you may have before you come!
  button:
    text: Connect with us
    href: https://fountaincitykc.churchcenter.com/people/forms/283554

apps:
  headline: Download Our App
  content: |-
    The Church Center app is a central hub that includes registrations for events, giving, volunteer schedules, and a church directory.
  buttons:
    - text: App Store
      href: https://apps.apple.com/us/app/church-center-app/id1357742931
      image: /media/apps/app-store.svg
    - text: Google Play
      href: https://play.google.com/store/apps/details?id=com.ministrycentered.churchcenter
      image: /media/apps/google-play.svg

social:
  - text: Instagram
    href: https://www.instagram.com/fountaincitychurch_kc/
    image: /media/social/instagram.svg
  - text: Facebook
    href: https://www.facebook.com/people/Fountain-City-Church/100070786269545/
    image: /media/social/facebook.svg
  - text: Youtube
    href: https://www.youtube.com/@fountaincitychurchkc9519/
    image: /media/social/youtube.svg
  - text: Podcast
    href: https://podcasts.apple.com/us/podcast/fountain-city-kc/id1528910234
    image: /media/social/podcast.svg
